# Generated by Django 3.2.8 on 2021-11-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='persons',
        ),
    ]
