# Generated by Django 3.2.8 on 2021-11-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20211108_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='file',
        ),
        migrations.AlterModelTable(
            name='table',
            table='Eco_Drivers',
        ),
    ]
